version: '3.8'
services:
  main:
    image: oep/image:latest
    build:
      context: .
      dockerfile: ./OrderEventProcessor/Dockerfile
    ports:
      - "8080:80"  # Adjust the port mapping as needed
    depends_on:
      - db
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=postgres;Username=postgres;Password=tomzo  # Modify this connection string

  db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tomzo
    ports:
      - "5432:5432"  # Adjust the port mapping as needed


  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq-container
    ports:
      - "5672:5672"  # RabbitMQ message port
    environment:
      - "RABBITMQ_DEFAULT_PASS=tomzo"
      - "RABBITMQ_DEFAULT_USER=tomzo"
      - "RABBITMQ_DEFAULT_VHOST=/"

